### PR TITLE
Fix bug in Rhai Event Handler

### LINKED ISSUE #75: Rhai Events are overriding each other
Hi!
Could be that I completely misunderstand events in this crate.
I've implemented a function that allows me to spawn a mod.
So via script, i can just spawn other mods.
and those spawned mods then get called the "on_init" function in their script!

problem is, as soon as there is more than just one at the same time, only one of them gets the init method called.

same thing for the Update call.
I can't use Recipients::All because i need to do some additional checks before calling on_update on that entity, so i use Recipient::Entity, and loop through all of them. and here the same problem!

~~Am I misunderstanding something or is this a "design flaw"?~~
Noticed that this is a bug in the rhai implementation. Lua did not behave Like this.

### PR DESCRIPTION
**Pull request by zwazel**
This should fix #75 

Also added a new example for Rhai.

### CODE REVIEW

**Comment by zwazel** [comment]
I just noticed that i also updated the Rhai version. please tell me if I should revert this change or not.

**Comment by zwazel** [comment]
I also just changed it so that i no longer get errors printed out when a function can't be found in a script.

as far as i can tell, this is a similar behaviour as in the Lua solution: https://github.com/makspll/bevy_mod_scripting/blob/75902486147e48b509e07752f713bfff459dba46/languages/bevy_mod_scripting_lua/src/lib.rs#L169-L172

**Comment by makspll** [comment]
Hi @zwazel PR looks good, great catch! Love the examples. Please see to the clippy errors and LGTM

**Comment by zwazel** [comment]
Glad I can help with this great crate!
I currently can't go on my PC, so i'll fix the clippy errros tomorrow!

I might also take a Look at how to tackle #74

**Comment by makspll** [comment]
Appreciate it a lot! no problem!

**Review by makspll — DISMISSED** [review]

**Review by makspll — APPROVED** [review]

**Comment by zwazel** [comment]
Hi, as far as I can tell the only clippy warning that I got was from lua derive. 
(I actually didnt get any locally, so kinda hard to reproduce, but that should have fixed it)

**Comment by makspll** [comment]
Yeah sorry about that, the CI runs on latest rust version meaning any new clippy warnings randomly popup on old code, I need to find a way to pick the clippy version somehow

**Pull request merged**
