### PR TITLE
feat: Complete Crate Re-write

### PR DESCRIPTION
**Pull request by makspll**

### CODE REVIEW

**Comment by makspll** [comment]
I now have most functionality back, I think I just need to reimplement metamethods for glam types, I.e. add sub mul

**Comment by shanecelis** [comment]
We wait with bated breath. God speed. :D

**Comment by makspll** [comment]
> We wait with bated breath. God speed. :D

It's soooooo close, I can't wait to get this out :D

**Comment by makspll** [comment]
Okay that's all the functionality complete, I still need to fix up tests, and clean up / make docs but I will move this into staging

**Pull request merged**
